root: "{{CLAM_ROOT=/tmp}}/webglem-userdata"
port: "{{CLAM_PORT=8080}}"
use_forwarded_host: "{{CLAM_USE_FORWARDED_HOST|bool=false}}" #(set to true or false, enable this if you run behind a properly configured reverse proxy only)
switchboard_forward_url: "{{CLAM_SWITCHBOARD_FORWARD_URL}}" #e.g. "https://switchboard.clarin.eu/#/glem/$BACKLINK/$MIMETYPE/grc"
debug: "{{CLAM_DEBUG|bool=false}}"
oauth: "{{CLAM_OAUTH|bool=false}}"
oauth_client_id: "{{CLAM_OAUTH_CLIENT_ID}}"
oauth_client_secret: "{{CLAM_OAUTH_CLIENT_SECRET}}"
oauth_client_url: "{{CLAM_OAUTH_CLIENT_URL}}"
oauth_auth_url: "{{CLAM_OAUTH_AUTH_URL}}"
oauth_token_url: "{{CLAM_OAUTH_TOKEN_URL}}"
oauth_userinfo_url: "{{CLAM_OAUTH_USERINFO_URL}}"
oauth_revoke_url: "{{CLAM_OAUTH_REVOKE_URL}}"
oauth_scope: "{{CLAM_OAUTH_SCOPE|json}}"
